# About the project

*Write a short description about the course and add a link to your GitHub repository here. This is an R Markdown (.Rmd) file so you should use R Markdown syntax.*

```{r}
# This is a so-called "R chunk" where you can write R code.
# Please ignore the following notes, they are here so I can access them easily. The part "text continues here will contain the required excercise.  
# Base notes: remember that when mean(mydata$var1) the $ is separating which variable you are computing.
# To assign value use X <- YZ where X is the object YZ the value assigned to it.
# seq() creates sequence of numbers (+1 by default) between the two arguments you pass. You can also assign the result of the sequence into an object eg. example_sequence <- seq(15,30)
# If you save the results of a function in an object, it is not printed, if you run function without assignment (<-) it is printed but not saved
# <- and =, 
# object, function, input, argument: objetc= input and output of function, 
# %<% pipe: with the pipe we can rewrite this: mean(data$var1) to library(tidyverse) mydata$var1 %<% mean() which should give ## [1] 2.5, keyboard shortcut CTRL+Shift+M
# lm() function, . sends the data to the second argument
# recap: $ selects column, <- assigns values or result to a variable, pipe, send data into a function.
# >, <, >=, <= comparison tools, most commonly inside filter() function
# to write a vertical bar | press alt + 7, | means 'or', & means 'and'
# combine function: c()
# %in% and c()
# Filtering for missing values (NAs) needs special care. eg. mydata %>% filter(is.na(var2)) or for rows where var2 is not missing mydata %>% filter(!is.na(var2)) ! means not
# excluding rows: "not equals" (!=) to keep missing values use | operator and the is.na() function.
# dividing columns: name of dataset$column wanted to change /2 if wanted division by 2 eg. typesdata$measurement/2
# mutate() = incorporates the change into the column, mutate () can also be used to create a new column with a singel constant value: can be used to calculate a difference for each existing dates
#CONTINUE FROM 2.9 CONDITIONAL CALCULATIONS
date()

```

So far it has been an adventure learning all this. 
I am yet to be sure if I have understood clearly everything and will admit needing my notes (above) to remember all the commands. 
Very interesting though. I expect to learn how to use R and Rstudio as well as Github to an extent where it will be useful for my studies.
This course was one of the suggested courses for the Contemporary Societies method courses. 
The R for Health Data Science and the Exercise Set 1 gave a good introduction to the R tools while I also feel like I will need much more work with R to fully understand what I am doing and to remember all the functions and tools introduced.
# https://github.com/evaeskelinen/IODS-project.git

